### GENERAL SETTINGS ###

# Site settings
title: CMU IPSUM Lab.
description: "AI for SE research at CMU"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/" #important: start with /
url: "http://cmu-ipsum"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url:
  - title: instagram
    url:
  - title: tumblr
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - 4665 Forbes Ave,
    - Pittsburgh, PA,
    - United States.


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Vincent Hellendoorn
    position: Assistant Professor
    text: <a href="https://www.isri.cmu.edu/people/core-faculty/hellendoorn-vincent.html">Webpage</a>
    img: vincent.jpg
      #   social:
      # - title: envelope #use for email address
      #   url: mailto:vhellendoorn@andrew.cmu.edu
      # - title: twitter
      #   url: http://twitter.com/vhellendoorn

  - name: Claire Le Goues
    position: Associate Professor
    text: <a href="https://clairelegoues.com">Webpage</a>
    img: julian.jpg

  - name: Nikitha Rao
    position: PhD Software Engineering, 2021
    text: <a href="https://raonikitha.github.io/">Webpage</a>
    img: nikitha.jpg

    - name: Sophia Kolak
    position: PhD Software Engineering, 2021 - (also <a href="https://squareslab.github.io/">SquaresLab</a>)
    text: <a href="https://sophiakolak.github.io">Webpage</a>
    img: sophia.jpg

   - name: Daye Nam
    position: PhD Software Engineering, 2018- (also <a href="http://www.cs.cmu.edu/~bam/">Myers group</a>)
    text: <a href="https://dayenam.com/">Webpage</a>

  - name: Aidan Yang
    position: PhD Software Engineering, 2021 - (also <a href="https://squareslab.github.io/">SquaresLab</a>)
    text: <a href="https://aidanby.github.io">Webpage</a>
    img: aidan.jpg










# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Programma, cura te ipsum! The IPSUM lab studies intelligent solutions for software engineering at Carnegie Mellon university. It is lead by Vincent Hellendoorn"
