### GENERAL SETTINGS ###

# Site settings
title: CMU IPSUM Lab.
description: "AI for SE research at CMU"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/" #important: start with /
url: "http://cmu-ipsum"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#0c1227" #00b3fe original "#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#004aad" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#000000"
  footer_content: "#000000"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url:
  - title: instagram
    url:
  - title: tumblr
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - 4665 Forbes Ave,
    - Pittsburgh, PA,
    - United States.


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
faculty:
  - name: Vincent Hellendoorn
    position: Assistant Professor
    text: <a href="https://www.isri.cmu.edu/people/core-faculty/hellendoorn-vincent.html">Webpage</a>
    img: vincent.jpg
    social:
      - title: envelope #use for email address
        url: mailto:vhellendoorn@andrew.cmu.edu
      - title: twitter
        url: http://twitter.com/vhellendoorn

aff_faculty:
  - name: Claire Le Goues
    position: Associate Professor
    text: <a href="https://clairelegoues.com">Webpage</a>
    img: julian.jpg
    social:
      - title: envelope #use for email address
        url: mailto:clegoues@andrew.cmu.edu
      - title: twitter
        url: http://twitter.com/clegoues

  - name: Ruben Martins
    position: Assistant Research Professor
    text: <a href="https://sat-group.github.io/ruben/">Webpage</a>
    img: ruben.jpg
    social:
      - title: envelope #use for email address
        url: mailto:rubenm@andrew.cmu.edu
      - title: twitter
        url: http://twitter.com/rubengmartins

  - name: Jonathan Aldrich
    position: Professor
    text: <a href="https://www.cs.cmu.edu/~aldrich/">Webpage</a>
    img: jonathan.jpg
    social:
      - title: envelope #use for email address
        url: mailto:jonathan.aldrich@cs.cmu.edu
      - title: twitter
        url: http://twitter.com/jaldrichpl


grad:
  - name: Aidan Yang
    position: PhD Software Engineering, 2021 - (also <a href="https://squareslab.github.io/">SquaresLab</a>)
    text: <a href="https://aidanby.github.io/">Webpage</a>
    img: aidan.jpg
    social:
      - title: envelope #use for email address
        url: mailto:aidan@cmu.edu
      - title: twitter
        url: http://twitter.com/aidanzhyang
  - name: Luis Gomes
    position: PhD Software Engineering, 2021
    text: <a href="https://www.cmuportugal.org/students/luis-filipe-fernandes-gomes/">Webpage</a>
    img: luis.jpg
    social:
      - title: envelope #use for email address
        url: mailto:lfgomes@andrew.cmu.edu
      # - title: twitter
      #   url: http://twitter.com/aidanzhyang
  - name: Nikitha Rao
    position: PhD Software Engineering, 2021
    text: <a href="https://raonikitha.github.io/">Webpage</a>
    img: nikitha.jpg
    social:
      - title: envelope #use for email address
        url: mailto:nikithar@andrew.cmu.edu
      # - title: twitter
      #   url: http://twitter.com/aidanzhyang
  - name: Sophia Kolak
    position: PhD Software Engineering, 2021 - (also <a href="https://squareslab.github.io/">SquaresLab</a>)
    text: <a href="https://sophiakolak.github.io">Webpage</a>
    img: sophia.jpg
    social:
      - title: envelope #use for email address
        url: mailto:sdkolak@andrew.cmu.edu
      - title: twitter
        url: http://twitter.com/kolaksophia
  - name: Daye Nam
    position: PhD Software Engineering, 2018- (also <a href="http://www.cs.cmu.edu/~bam/">Myers group</a>)
    text: <a href="https://dayenam.com/">Webpage</a>
    img: daye.jpg
    social:
      - title: envelope #use for email address
        url: mailto:dayen@andrew.cmu.edu
      - title: twitter
        url: http://twitter.com/daye_nam


# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Programma, cura te ipsum!"
