### GENERAL SETTINGS ###

# Site settings
title: CMU IPSUM Lab.
description: "AI for SE research at CMU"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://cmu-ipsum.github.io/"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url:
  - title: instagram
    url:
  - title: tumblr
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Some Ave, 987,
    - 23890, New York,
    - United States.
email: hello@solidtheme.com
tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
faculty:
  - name: Vincent Hellendoorn
    position: Chief Culinary Officer
    web: https://www.isri.cmu.edu/people/core-faculty/hellendoorn-vincent.html
 #   img: bogdan.jpg
    social:
      - title: envelope #use for email address
        url: mailto:vasilescu@cmu.edu
      - title: twitter
        url: http://twitter.com/b_vasilescu
      - title: link
        url: http://bvasiles.github.io

affilfaculty:
  - name: Claire Le Goues
    position: Affiliate; CMU, ISR
    web: https://clairelegoues.com
#    img: claire.jpg
    strudel: none
    social:
#      - title: envelope #use for email address
#        url: mailto:name@domain.com
      - title: twitter
        url: https://twitter.com/clegoues
      - title: link
        url: https://clairelegoues.com

grads:
  - name: Aidan Yang
    position: PhD Software Engineering, 2021 - (also <a href="https://squareslab.github.io/">SquaresLab</a>)
#    img: hongbo.jpg
    social:
      - title: envelope #use for email address
        url: mailto:aidan@cmu.edu
      - title: twitter
        url: http://twitter.com/aidanzhyang
      - title: link
        url: aidanby.github.io
   
   - name: Nikitha Rao
    position: PhD Software Engineering, 2021
#    img: jeremy.jpg
    social:
#      - title: envelope #use for email address
#        url: mailto:jlacomis@cmu.edu
#      - title: twitter
#        url: http://twitter.com/jlacomis
      - title: link
        url: https://raonikitha.github.io/
        
    - name: Sophia Kolak
    position: PhD Software Engineering, 2021
#    img: jeremy.jpg
    social:
#      - title: envelope #use for email address
#        url: mailto:jlacomis@cmu.edu
#      - title: twitter
#        url: http://twitter.com/jlacomis
      - title: link
        url: https://sophiakolak.github.io/

        
   - name: Daye Nam
    position: PhD Software Engineering, 2018- (also <a href="http://www.cs.cmu.edu/~bam/">Myers group</a>)
#    img: daye.jpg
    social:
      - title: envelope #use for email address
        url: mailto:dayen@andrew.cmu.edu
#      - title: twitter
#        url: http://twitter.com/handle
      - title: link
        url: https://dayenam.com/
  
        
  

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Programma, cura te ipsum!
The IPSUM lab studies intelligent solutions for software engineering at Carnegie Mellon university. It is lead by Vincent Hellendoorn"



