### GENERAL SETTINGS ###

# Site settings
title: CMU IPSUM Lab.
description: "AI for SE research at CMU"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/" #important: start with /
url: "http://cmu-ipsum"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#0c1227" #00b3fe original "#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#004aad" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#000000"
  footer_content: "#000000"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
# social:
#   - title: dribbble
#     url:
#   - title: facebook
#     url:
#   - title: twitter
#     url:
#   - title: instagram
#     url:
#   - title: tumblr
#     url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - 4665 Forbes Ave,
    - Pittsburgh, PA,
    - United States.


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
faculty:
  - name: Vincent Hellendoorn
    position: Assistant Professor
    web: https://www.isri.cmu.edu/people/core-faculty/hellendoorn-vincent.html
    img: vincent.jpg
    social:
      - title: envelope #use for email address
        url: mailto:vhellendoorn@andrew.cmu.edu
      - title: twitter
        url: http://twitter.com/vhellendoorn

aff_faculty:

  - name: Bogdan Vasilescu
    position: ISR; Co-advising Daye Nam
    web: https://bvasiles.github.io/
    img: bogdan.jpg
    social:
      - title: envelope 
        url: mailto:vasilescu@cmu.edu
      - title: twitter
        url: http://twitter.com/b_vasilescu

  - name: Claire Le Goues
    position: ISR; Co-adivsing Aidan Yang & Sophia Kolak
    web: https://clairelegoues.com
    img: claire.jpg
    social:
      - title: envelope 
        url: mailto:clegoues@andrew.cmu.edu
      - title: twitter
        url: http://twitter.com/clegoues

  - name: Jonathan Aldrich
    position: ISR; Co-advising Luis Gomes
    web: https://www.cs.cmu.edu/~aldrich/
    img: jonathan.jpg
    social:
      - title: envelope 
        url: mailto:jonathan.aldrich@cs.cmu.edu
      - title: twitter
        url: http://twitter.com/jaldrichpl

  - name: Ruben Martins
    position: CSD; Co-advising Aidan Yang & Sophia Kolak
    web: https://sat-group.github.io/ruben/
    img: ruben.jpg
    social:
      - title: envelope 
        url: mailto:rubenm@andrew.cmu.edu
      - title: twitter
        url: http://twitter.com/rubengmartins



grad:
  - name: Aidan Yang
    position: PhD Software Engineering, 2021 (also <a href="https://squareslab.github.io/">SquaresLab</a>)
    web: https://aidanby.github.io/
    img: aidan.jpg
    social:
      - title: envelope #use for email address
        url: mailto:aidan@cmu.edu
      - title: twitter
        url: http://twitter.com/aidanzhyang
  - name: Luis Gomes
    position: PhD Software Engineering, 2021 (also <a href="https://www.cs.cmu.edu/~aldrich/">Aldrich group</a>))
    web: https://www.cmuportugal.org/students/luis-filipe-fernandes-gomes/
    img: luis.jpg
    social:
      - title: envelope #use for email address
        url: mailto:lfgomes@andrew.cmu.edu
  - name: Manisha Mukherjee
    position: PhD Software Engineering, 2021
    web: https://www.linkedin.com/in/manisha-mukherjee-18472284
    img: manisha.jpg
    social:
      - title: envelope #use for email address
        url: mailto:mmukherj@andrew.cmu.edu
  - name: Nikitha Rao
    position: PhD Software Engineering, 2021
    web: https://raonikitha.github.io/
    img: nikitha.jpg
    social:
      - title: envelope #use for email address
        url: mailto:nikithar@andrew.cmu.edu
  - name: Sophia Kolak
    position: PhD Software Engineering, 2021 - (also <a href="https://squareslab.github.io/">SquaresLab</a>)
    web: https://sophiakolak.github.io
    img: sophia.jpg
    social:
      - title: envelope #use for email address
        url: mailto:sdkolak@andrew.cmu.edu
      - title: twitter
        url: http://twitter.com/kolaksophia
  - name: Daye Nam
    position: PhD Software Engineering, 2018- (also <a href="http://www.cs.cmu.edu/~bam/">Myers group</a>)
    web: https://dayenam.com/
    img: daye.jpg
    social:
      - title: envelope #use for email address
        url: mailto:dayen@andrew.cmu.edu
      - title: twitter
        url: http://twitter.com/daye_nam


# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Programma, cura te ipsum!"
